apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: maven-pipeline-run
spec:
  pipelineRef:
    name: maven-pipeline
  resources:
  - name: git-repo
    resourceRef:
      name: spring-petclinic-repo
  - name: image
    resourceRef:
      name: spring-petclinic-image
  workspaces:
    - name: maven-repo
      persistentvolumeclaim:
        claimName: repo-pvc
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: workspace-pvc
