apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: mobydock-app
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.ssh_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.head_commit.id)